/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getHealth"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/planning-sessions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["createPlanningSession"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/planning-sessions/{sessionId}/messages": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["createPlanningRefinement"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/planning-sessions/{sessionId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getPlanningSession"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/planning-jobs/{jobId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getPlanningJob"];
    put?: never;
    post?: never;
    delete: operations["cancelPlanningJob"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    HealthResponse: {
      /** @enum {string} */
      status: "ok";
      service: string;
      version: string;
    };
    PlanningSessionAccepted: {
      /** Format: uuid */
      id: string;
      /** Format: date-time */
      createdAt: string;
      job: components["schemas"]["PlanningJobAccepted"];
    };
    PlanningJobAccepted: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      sessionId: string;
      /** @enum {string} */
      status: "queued";
      /** Format: date-time */
      createdAt: string;
      statusUrl: string;
      eventsUrl?: null;
    };
    ErrorResponse: {
      detail: string;
    };
    PlanningRefinementAccepted: {
      /** Format: uuid */
      sessionId: string;
      /** Format: uuid */
      messageId: string;
      job: components["schemas"]["PlanningJobAccepted"];
    };
    PlanningRefinementRequest: {
      content: string;
    };
    PlanningSession: {
      /** Format: uuid */
      id: string;
      initialRequest: {
        destination: string;
        durationDays: number;
        tripBrief: string;
        /** @default en-GB */
        locale: string;
      };
      messages: components["schemas"]["PlanningSessionMessage"][];
      currentRevision: components["schemas"]["PlanningSessionRevision"];
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    PlanningSessionMessage: {
      /** Format: uuid */
      id: string;
      turnNumber: number;
      content: string;
      /** Format: uuid */
      jobId: string;
      /** Format: date-time */
      createdAt: string;
    };
    PlanningSessionRevision: {
      revisionNumber: number;
      /** Format: uuid */
      jobId: string;
      result: components["schemas"]["PlanningResult"];
      /** Format: date-time */
      createdAt: string;
    } | null;
    PlanningResult: {
      /** @enum {number} */
      schemaVersion: 1;
      title: string;
      destination: components["schemas"]["Destination"];
      durationDays: number;
      summary: string;
      /** @default [] */
      assumptions: string[];
      /** @default [] */
      days: components["schemas"]["DraftDay"][];
      /** @default [] */
      checklistSuggestions: components["schemas"]["ChecklistSuggestion"][];
      /** @default [] */
      referenceLinks: components["schemas"]["ReferenceLink"][];
      /** @default [] */
      warnings: string[];
    };
    Destination: {
      name: string;
      country: string;
      timezone: string;
    };
    DraftDay: {
      dayNumber: number;
      title: string;
      description: string;
      /** @default [] */
      items: components["schemas"]["DraftItem"][];
    };
    DraftItem: {
      draftId: string;
      /** @enum {string} */
      type: "place" | "activity" | "meal" | "transport" | "note";
      title: string;
      description: string;
      /** @default null */
      suggestedStartTime: string | null;
      /** @default null */
      estimatedDurationMinutes: number | null;
      /** @default null */
      category: string | null;
      location?: components["schemas"]["SuggestedLocation"];
      reason: string;
      /** @default [] */
      sources: components["schemas"]["Source"][];
    };
    /** @default null */
    SuggestedLocation: {
      name: string;
      searchQuery: string;
      /** @default null */
      latitude: number | null;
      /** @default null */
      longitude: number | null;
      /** @default null */
      externalPlaceId: string | null;
    } | null;
    Source: {
      title: string;
      /** Format: uri */
      url: string;
    };
    ChecklistSuggestion: {
      title: string;
    };
    ReferenceLink: {
      title: string;
      /** Format: uri */
      url: string;
    };
    PlanningJobRunning: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      sessionId: string;
      /** @enum {string} */
      status: "queued" | "researching" | "drafting" | "validating";
      progress: components["schemas"]["PlanningJobProgress"];
      /** Format: date-time */
      updatedAt: string;
    };
    PlanningJobProgress: {
      stage: string;
      message: string;
    };
    PlanningJobCompleted: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      sessionId: string;
      /** @enum {string} */
      status: "completed";
      revisionNumber: number;
      result: components["schemas"]["PlanningResult"];
      /** Format: date-time */
      updatedAt: string;
    };
    PlanningJobCancelled: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      sessionId: string;
      /** @enum {string} */
      status: "cancelled";
      /** Format: date-time */
      updatedAt: string;
    };
    PlanningJobFailed: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      sessionId: string;
      /** @enum {string} */
      status: "failed";
      message: string;
      /** Format: date-time */
      updatedAt: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getHealth: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Service is healthy. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "status": "ok",
           *       "service": "wafflelog-trip-api",
           *       "version": "0.1.0"
           *     }
           */
          "application/json": components["schemas"]["HealthResponse"];
        };
      };
    };
  };
  createPlanningSession: {
    parameters: {
      query?: never;
      header: {
        "idempotency-key": string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        /**
         * @example {
         *       "destination": "Kyoto, Japan",
         *       "durationDays": 3,
         *       "tripBrief": "We are travelling from 12 October 2026. Include temples, local restaurants, walkable neighbourhoods, and a mix of famous sights and quieter local areas. Avoid very early starts.",
         *       "locale": "en-GB"
         *     }
         */
        "application/json": {
          destination: string;
          durationDays: number;
          tripBrief: string;
          /** @default en-GB */
          locale?: string;
        };
      };
    };
    responses: {
      /** @description Planning session and its initial job accepted. */
      202: {
        headers: {
          /** @description Suggested polling interval in seconds. */
          "Retry-After"?: string;
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "id": "18f2a569-3ff3-4b76-93e5-6fffe4a1f76b",
           *       "createdAt": "2026-07-25T12:00:00.000Z",
           *       "job": {
           *         "id": "6f9619ff-8b86-4b7c-aad2-1f6f90fdb234",
           *         "sessionId": "18f2a569-3ff3-4b76-93e5-6fffe4a1f76b",
           *         "status": "queued",
           *         "createdAt": "2026-07-25T12:00:00.000Z",
           *         "statusUrl": "https://api.example.com/v1/planning-jobs/6f9619ff-8b86-4b7c-aad2-1f6f90fdb234",
           *         "eventsUrl": null
           *       }
           *     }
           */
          "application/json": components["schemas"]["PlanningSessionAccepted"];
        };
      };
      /** @description A valid Supabase access token is required. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "detail": "Authentication required."
           *     }
           */
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description The idempotency key has already been used for another request. */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "detail": "Idempotency key has already been used for another request."
           *     }
           */
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Request validation failed. */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "detail": "Request validation failed."
           *     }
           */
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Agent Server could not accept the planning job. */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "detail": "Planning service is unavailable."
           *     }
           */
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  createPlanningRefinement: {
    parameters: {
      query?: never;
      header: {
        "idempotency-key": string;
      };
      path: {
        sessionId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        /**
         * @example {
         *       "content": "Make day two more relaxed and add a garden."
         *     }
         */
        "application/json": components["schemas"]["PlanningRefinementRequest"];
      };
    };
    responses: {
      /** @description Planning refinement accepted. */
      202: {
        headers: {
          /** @description Suggested job polling interval in seconds. */
          "Retry-After"?: string;
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "sessionId": "18f2a569-3ff3-4b76-93e5-6fffe4a1f76b",
           *       "messageId": "40a910c4-5a46-47cf-aac4-22896fdf2638",
           *       "job": {
           *         "id": "6f9619ff-8b86-4b7c-aad2-1f6f90fdb234",
           *         "sessionId": "18f2a569-3ff3-4b76-93e5-6fffe4a1f76b",
           *         "status": "queued",
           *         "createdAt": "2026-07-25T12:00:00.000Z",
           *         "statusUrl": "https://api.example.com/v1/planning-jobs/6f9619ff-8b86-4b7c-aad2-1f6f90fdb234",
           *         "eventsUrl": null
           *       }
           *     }
           */
          "application/json": components["schemas"]["PlanningRefinementAccepted"];
        };
      };
      /** @description A valid Supabase access token is required. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Planning session not found. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description The idempotency key conflicts with an earlier request. */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Request validation failed. */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Agent Server could not accept the refinement. */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  getPlanningSession: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        sessionId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The persisted planning conversation and latest revision. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "id": "18f2a569-3ff3-4b76-93e5-6fffe4a1f76b",
           *       "initialRequest": {
           *         "destination": "Kyoto, Japan",
           *         "durationDays": 3,
           *         "tripBrief": "We are travelling from 12 October 2026. Include temples, local restaurants, walkable neighbourhoods, and a mix of famous sights and quieter local areas. Avoid very early starts.",
           *         "locale": "en-GB"
           *       },
           *       "messages": [
           *         {
           *           "id": "40a910c4-5a46-47cf-aac4-22896fdf2638",
           *           "turnNumber": 1,
           *           "content": "We are travelling from 12 October 2026. Include temples, local restaurants, walkable neighbourhoods, and a mix of famous sights and quieter local areas. Avoid very early starts.",
           *           "jobId": "6f9619ff-8b86-4b7c-aad2-1f6f90fdb234",
           *           "createdAt": "2026-07-25T12:00:00.000Z"
           *         }
           *       ],
           *       "currentRevision": {
           *         "revisionNumber": 1,
           *         "jobId": "6f9619ff-8b86-4b7c-aad2-1f6f90fdb234",
           *         "result": {
           *           "schemaVersion": 1,
           *           "title": "Three days in Kyoto",
           *           "destination": {
           *             "name": "Kyoto",
           *             "country": "Japan",
           *             "timezone": "Asia/Tokyo"
           *           },
           *           "durationDays": 3,
           *           "summary": "A balanced Kyoto itinerary combining landmark temples, local food, and relaxed neighbourhood walks.",
           *           "assumptions": [
           *             "Travellers are comfortable using public transport.",
           *             "Accommodation is near central Kyoto."
           *           ],
           *           "days": [
           *             {
           *               "dayNumber": 1,
           *               "title": "Eastern Kyoto",
           *               "description": "Temples, traditional streets, and an evening in Gion.",
           *               "items": [
           *                 {
           *                   "draftId": "day-1-kiyomizu",
           *                   "type": "place",
           *                   "title": "Kiyomizu-dera",
           *                   "description": "Visit the hillside temple before walking through Sannenzaka and Ninenzaka.",
           *                   "suggestedStartTime": "09:00",
           *                   "estimatedDurationMinutes": 120,
           *                   "category": "temple",
           *                   "location": {
           *                     "name": "Kiyomizu-dera",
           *                     "searchQuery": "Kiyomizu-dera Kyoto",
           *                     "latitude": 34.9949,
           *                     "longitude": 135.785,
           *                     "externalPlaceId": null
           *                   },
           *                   "reason": "It combines an important Kyoto landmark with a scenic historic district.",
           *                   "sources": [
           *                     {
           *                       "title": "Kiyomizu-dera official website",
           *                       "url": "https://www.kiyomizudera.or.jp/en/"
           *                     }
           *                   ]
           *                 },
           *                 {
           *                   "draftId": "day-1-gion",
           *                   "type": "activity",
           *                   "title": "Evening walk through Gion",
           *                   "description": "Explore Hanamikoji Street and the Shirakawa canal at a relaxed pace.",
           *                   "suggestedStartTime": "17:30",
           *                   "estimatedDurationMinutes": 90,
           *                   "category": "walking",
           *                   "location": {
           *                     "name": "Gion",
           *                     "searchQuery": "Gion Kyoto",
           *                     "latitude": 35.0037,
           *                     "longitude": 135.7758,
           *                     "externalPlaceId": null
           *                   },
           *                   "reason": "The neighbourhood is atmospheric in the early evening and easy to explore on foot.",
           *                   "sources": []
           *                 }
           *               ]
           *             },
           *             {
           *               "dayNumber": 2,
           *               "title": "Arashiyama",
           *               "description": "An early bamboo-grove visit followed by riverside scenery.",
           *               "items": [
           *                 {
           *                   "draftId": "day-2-arashiyama",
           *                   "type": "place",
           *                   "title": "Arashiyama Bamboo Grove",
           *                   "description": "Walk through the grove and continue to the nearby riverside.",
           *                   "suggestedStartTime": "09:00",
           *                   "estimatedDurationMinutes": 90,
           *                   "category": "nature",
           *                   "location": {
           *                     "name": "Arashiyama Bamboo Grove",
           *                     "searchQuery": "Arashiyama Bamboo Grove Kyoto",
           *                     "latitude": 35.017,
           *                     "longitude": 135.6713,
           *                     "externalPlaceId": null
           *                   },
           *                   "reason": "Arriving in the morning provides a calmer experience without requiring a very early start.",
           *                   "sources": []
           *                 }
           *               ]
           *             },
           *             {
           *               "dayNumber": 3,
           *               "title": "Northern Kyoto",
           *               "description": "Golden Pavilion and a leisurely final afternoon in the city.",
           *               "items": [
           *                 {
           *                   "draftId": "day-3-kinkakuji",
           *                   "type": "place",
           *                   "title": "Kinkaku-ji",
           *                   "description": "See the Golden Pavilion and walk around its landscaped garden.",
           *                   "suggestedStartTime": "10:00",
           *                   "estimatedDurationMinutes": 90,
           *                   "category": "temple",
           *                   "location": {
           *                     "name": "Kinkaku-ji",
           *                     "searchQuery": "Kinkaku-ji Kyoto",
           *                     "latitude": 35.0394,
           *                     "longitude": 135.7292,
           *                     "externalPlaceId": null
           *                   },
           *                   "reason": "It is one of Kyoto's defining sights and fits a relaxed final day.",
           *                   "sources": []
           *                 }
           *               ]
           *             }
           *           ],
           *           "checklistSuggestions": [
           *             {
           *               "title": "Load an IC transport card"
           *             },
           *             {
           *               "title": "Pack comfortable walking shoes"
           *             }
           *           ],
           *           "referenceLinks": [
           *             {
           *               "title": "Kyoto City Official Travel Guide",
           *               "url": "https://kyoto.travel/en/"
           *             }
           *           ],
           *           "warnings": [
           *             "Opening hours and admission rules should be checked before travel."
           *           ]
           *         },
           *         "createdAt": "2026-07-25T12:03:00.000Z"
           *       },
           *       "createdAt": "2026-07-25T12:00:00.000Z",
           *       "updatedAt": "2026-07-25T12:03:00.000Z"
           *     }
           */
          "application/json": components["schemas"]["PlanningSession"];
        };
      };
      /** @description A valid Supabase access token is required. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Planning session not found. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Session ID validation failed. */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  getPlanningJob: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        jobId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Current planning job status. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "id": "6f9619ff-8b86-4b7c-aad2-1f6f90fdb234",
           *       "sessionId": "18f2a569-3ff3-4b76-93e5-6fffe4a1f76b",
           *       "status": "completed",
           *       "revisionNumber": 1,
           *       "result": {
           *         "schemaVersion": 1,
           *         "title": "Three days in Kyoto",
           *         "destination": {
           *           "name": "Kyoto",
           *           "country": "Japan",
           *           "timezone": "Asia/Tokyo"
           *         },
           *         "durationDays": 3,
           *         "summary": "A balanced Kyoto itinerary combining landmark temples, local food, and relaxed neighbourhood walks.",
           *         "assumptions": [
           *           "Travellers are comfortable using public transport.",
           *           "Accommodation is near central Kyoto."
           *         ],
           *         "days": [
           *           {
           *             "dayNumber": 1,
           *             "title": "Eastern Kyoto",
           *             "description": "Temples, traditional streets, and an evening in Gion.",
           *             "items": [
           *               {
           *                 "draftId": "day-1-kiyomizu",
           *                 "type": "place",
           *                 "title": "Kiyomizu-dera",
           *                 "description": "Visit the hillside temple before walking through Sannenzaka and Ninenzaka.",
           *                 "suggestedStartTime": "09:00",
           *                 "estimatedDurationMinutes": 120,
           *                 "category": "temple",
           *                 "location": {
           *                   "name": "Kiyomizu-dera",
           *                   "searchQuery": "Kiyomizu-dera Kyoto",
           *                   "latitude": 34.9949,
           *                   "longitude": 135.785,
           *                   "externalPlaceId": null
           *                 },
           *                 "reason": "It combines an important Kyoto landmark with a scenic historic district.",
           *                 "sources": [
           *                   {
           *                     "title": "Kiyomizu-dera official website",
           *                     "url": "https://www.kiyomizudera.or.jp/en/"
           *                   }
           *                 ]
           *               },
           *               {
           *                 "draftId": "day-1-gion",
           *                 "type": "activity",
           *                 "title": "Evening walk through Gion",
           *                 "description": "Explore Hanamikoji Street and the Shirakawa canal at a relaxed pace.",
           *                 "suggestedStartTime": "17:30",
           *                 "estimatedDurationMinutes": 90,
           *                 "category": "walking",
           *                 "location": {
           *                   "name": "Gion",
           *                   "searchQuery": "Gion Kyoto",
           *                   "latitude": 35.0037,
           *                   "longitude": 135.7758,
           *                   "externalPlaceId": null
           *                 },
           *                 "reason": "The neighbourhood is atmospheric in the early evening and easy to explore on foot.",
           *                 "sources": []
           *               }
           *             ]
           *           },
           *           {
           *             "dayNumber": 2,
           *             "title": "Arashiyama",
           *             "description": "An early bamboo-grove visit followed by riverside scenery.",
           *             "items": [
           *               {
           *                 "draftId": "day-2-arashiyama",
           *                 "type": "place",
           *                 "title": "Arashiyama Bamboo Grove",
           *                 "description": "Walk through the grove and continue to the nearby riverside.",
           *                 "suggestedStartTime": "09:00",
           *                 "estimatedDurationMinutes": 90,
           *                 "category": "nature",
           *                 "location": {
           *                   "name": "Arashiyama Bamboo Grove",
           *                   "searchQuery": "Arashiyama Bamboo Grove Kyoto",
           *                   "latitude": 35.017,
           *                   "longitude": 135.6713,
           *                   "externalPlaceId": null
           *                 },
           *                 "reason": "Arriving in the morning provides a calmer experience without requiring a very early start.",
           *                 "sources": []
           *               }
           *             ]
           *           },
           *           {
           *             "dayNumber": 3,
           *             "title": "Northern Kyoto",
           *             "description": "Golden Pavilion and a leisurely final afternoon in the city.",
           *             "items": [
           *               {
           *                 "draftId": "day-3-kinkakuji",
           *                 "type": "place",
           *                 "title": "Kinkaku-ji",
           *                 "description": "See the Golden Pavilion and walk around its landscaped garden.",
           *                 "suggestedStartTime": "10:00",
           *                 "estimatedDurationMinutes": 90,
           *                 "category": "temple",
           *                 "location": {
           *                   "name": "Kinkaku-ji",
           *                   "searchQuery": "Kinkaku-ji Kyoto",
           *                   "latitude": 35.0394,
           *                   "longitude": 135.7292,
           *                   "externalPlaceId": null
           *                 },
           *                 "reason": "It is one of Kyoto's defining sights and fits a relaxed final day.",
           *                 "sources": []
           *               }
           *             ]
           *           }
           *         ],
           *         "checklistSuggestions": [
           *           {
           *             "title": "Load an IC transport card"
           *           },
           *           {
           *             "title": "Pack comfortable walking shoes"
           *           }
           *         ],
           *         "referenceLinks": [
           *           {
           *             "title": "Kyoto City Official Travel Guide",
           *             "url": "https://kyoto.travel/en/"
           *           }
           *         ],
           *         "warnings": [
           *           "Opening hours and admission rules should be checked before travel."
           *         ]
           *       },
           *       "updatedAt": "2026-07-25T12:03:00.000Z"
           *     }
           */
          "application/json":
            | components["schemas"]["PlanningJobRunning"]
            | components["schemas"]["PlanningJobCompleted"]
            | components["schemas"]["PlanningJobCancelled"]
            | components["schemas"]["PlanningJobFailed"];
        };
      };
      /** @description A valid Supabase access token is required. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "detail": "Authentication required."
           *     }
           */
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Planning job not found. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "detail": "Planning job not found."
           *     }
           */
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Job ID validation failed. */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "detail": "Request validation failed."
           *     }
           */
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Agent Server could not return the planning job. */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "detail": "Planning service is unavailable."
           *     }
           */
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  cancelPlanningJob: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        jobId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Planning job cancelled. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "id": "6f9619ff-8b86-4b7c-aad2-1f6f90fdb234",
           *       "sessionId": "18f2a569-3ff3-4b76-93e5-6fffe4a1f76b",
           *       "status": "cancelled",
           *       "updatedAt": "2026-07-25T12:01:00.000Z"
           *     }
           */
          "application/json":
            | components["schemas"]["PlanningJobRunning"]
            | components["schemas"]["PlanningJobCompleted"]
            | components["schemas"]["PlanningJobCancelled"]
            | components["schemas"]["PlanningJobFailed"];
        };
      };
      /** @description A valid Supabase access token is required. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "detail": "Authentication required."
           *     }
           */
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Planning job not found. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "detail": "Planning job not found."
           *     }
           */
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Job ID validation failed. */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "detail": "Request validation failed."
           *     }
           */
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Agent Server could not cancel the planning job. */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "detail": "Planning service is unavailable."
           *     }
           */
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
}
